### PR TITLE
new change

### PR DESCRIPTION
**Pull request by UKQIDA**
- added an AsynchronousFileChannel and re-used inside the method
- added EBI repository to adapt pride-core migration

### CODE REVIEW

**Comment by mbdebian** [comment]
I'd like to thank you for your interest and time to make this pull request, where we'd like to point out a few issues.
@UKQIDA , please, could you review the code in this pull request after @Tobias-Ternent and myself went through it, and we made the following changes:
- Line ending character
- New lines
- Comments
- Variable names
- Empty code blocks removed
- Unused imports have been removed

And, by isolating the contributed changes down to the following method
`public String getStartTag(IndexElement element) throws IOException`
we suspected that GZip file support was borken, and indeed it is, as you can see in the unit test reports we ran on our side (see attached screen capture)
We would need this to be fixed before accepting this pull request, then, we can test its performance to establish the improvement.
Thanks.
screen shot 2017-03-31 at 12 30 48

**Comment by UKQIDA** [comment]
Hi, @mbdebian and @Tobias-Ternent, I've fixed the bugs in previous commit and could you please check it?
Thanks

**Comment by mbdebian** [comment]
Everything looks great!
Thanks a lot for your pull request.

**Comment by Tobias-Ternent** [comment]
@UKQIDA We have merged your pull request into Master now, and have made a new release: version 0.21. Sorry for the slight delay in doing this, we had some production issues recently in the team that had higher priority.

**Pull request merged**
